name: Deploy EDP Overlay

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, edp-overlay]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload test overlay
        uses: actions/upload-pages-artifact@v3
        with:
          path: C:\EDP\Overlays\_github_test

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
